config/routes.rb
Rails.application.routes.draw do

  resources :publications
  devise_for :users

  root 'welcome#index'
  get '/new'=>'welcome#new'
  get '/lock_unlock' => 'user#lock_unlock'
  get '/user' => 'user#index'
  get '/user/new' => 'user#new'
  get '/user/:id/edit_password' => 'user#edit_password'
  post '/user/:id/update_password' => 'user#update_password'
  post '/user' => 'user#create'

  post 'message' => 'welcome#message'

  get '/blinds/new' => 'blinds#new'
  get '/blinds' => 'blinds#index'
  get '/blinds/:id/edit' => 'blinds#edit'
  get '/blinds/:id' => 'blinds#show'
  get '/blinds/:id/delete' =>'blinds#delete'
  post '/blinds/:id/update' => 'blinds#update'
  post 'blinds' => 'blinds#create'

  get '/familiars/:id/delete' => 'familiars#delete'
  get '/familiars/:id/edit' => 'familiars#edit'
  post 'familiars' => 'familiars#create'
  post '/familiars/:id/update' => 'familiars#update'

  get '/blinds/:id/rehabilitations' => "rehabilitations#index"
  get 'rehabilitations/:id/delete' => 'rehabilitations#delete'
  post 'rehabilitations' => 'rehabilitations#create'

  get '/reports' => 'blinds#reports'

  get '/publications/new' => 'publications#new'
  get '/publications' => 'publications#index'
  post 'publications' => 'publications#create'
  get '/publications/:id' => 'publications#show'
  get 'publications/index'

end

app/models/publication.rb
class Publication < ActiveRecord::Base


validates :title, :presence => {:message => "Usted debe ingresar un titulo"},:uniqueness => {:message => "Usted ha ingresado un titlulo repetido"}
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    user_auth
    @publications = Publication.all.order('updated_at DESC')
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    user_auth
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    user_auth
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to "/publications", notice: 'Publication was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to "/publications", notice: 'Publication was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :description, :initialDate, :finalDate, :showP, :image_path)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<script type="text/javascript">
    $(document).on('ready', function () {
        $('.ui.accordion').accordion();
        $('.ui.checkbox').checkbox();
    });
</script>
<%if current_user.has_role? :Administrador or current_user.has_role? :Modificador %>
<%= form_for(@publication) do |f| %>

  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %>:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui form container ">
    <div class="ui   segment">
      <div class="ui header">
          Formulario de Publicaciones
      </div>
      <div class="ui divider"> </div>
        <div class="field">
          <%= f.label :"ruta de la imagen" %>
          <%= f.text_field :image_path%>
        </div>

        <div class="field">
          <%= f.label :titulo %>
          <%= f.text_field :title%>
        </div>
        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description %>
        </div>
        <div class="two fields">
          <div class="field">
            <%= f.label :initialDate %>
            <%= f.date_field :initialDate %>
          </div>
          <div class="field">
            <%= f.label :finalDate %>
            <%= f.date_field :finalDate %>
          </div>
        </div>
        <div class="inline field">
        <div class="ui toggle checkbox">
          <%= f.check_box :showP %>
          <%= f.label :Activo %>
        </div>
      </div>
        <div class="ui center aligned basic segment">
        <div class="actions">
          <%= f.submit "Guardar",class:"ui green fluid button" %>
        </div>
    </div>
  </div>
</div>
<% end %>
<%else%>
     <div class="ui segment">
      <h1>No deberias estar aqui</h1>
      </div>
<%end%>

app/views/publications/edit.html.erb
<%= render 'form' %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>
<script type="text/javascript">
    $(document).on('ready', function () {
        $('.ui.accordion').accordion();
    });
</script>

<div class="ui form container ">
  <div class="ui   segment">
    <div class="ui horizontal divider"><h5>Publicaciones Activas</h5></div>
            <div class="ui four column grid">
            <% @publications.each do |publication| %>

            <% if publication.showP%>
            <div class="column">
              <div class="ui fluid card">
                  <img class="ui fluid image"  src="<%= publication.image_path %>" width="178" height="180">
                  <div class="content">
                    <h2 class="header"><%= publication.title %></h2>
                    <div class="ui divider"></div>
                      Fecha: <%= publication.initialDate %> al <%= publication.finalDate %>
                    <div class="ui divider"></div>
                      <%if current_user.has_role? :Administrador or current_user.has_role? :Modificador %>
                      <%= link_to 'Editar', edit_publication_path(publication),class:"ui yellow mini button" %>
                      <%= link_to 'Eliminar', publication, method: :delete, data: { confirm: 'Are you sure?' } ,class:"ui red mini  button"  %>
                      <%end%>
                      <div class="ui divider"></div>
                    <div class="ui accordion">
                        <div class="title"><i class="dropdown icon"></i> Descripcion </div>
                        <div class="content">
                          <p class="transition hidden"><%= publication.description %></p>
                        </div>
                    </div>
                  </div>
              </div>

            </div>
          <% end %>
          <% end%>
        </div>
         <div class="ui horizontal divider"><h5>Publicaciones Inactivas</h5></div>
         <div class="ui four column grid">
             <% @publications.each do |publication| %>
               <tr>
                 <% if !publication.showP%>
                 <div class="column">
                   <div class="ui fluid card">
                     <img class="ui fluid image"  src="<%= publication.image_path %>"  width="178" height="180">
                       <div class="content">
                         <h2 class="header"><%= publication.title %></h2>
                         <div class="ui divider"></div>
                           Fecha: <%= publication.initialDate %> al <%= publication.finalDate %>
                         <div class="ui divider"></div>
                         <%if current_user.has_role? :Administrador or current_user.has_role? :Modificador %>
                         <%= link_to 'Editar', edit_publication_path(publication),class:"ui yellow mini button" %>
                         <%= link_to 'Eliminar', publication, method: :delete, data: { confirm: 'Are you sure?' } ,class:"ui red mini  button"  %>
                         <%end%>
                         <div class="ui divider"></div>
                         <div class="ui accordion">
                             <div class="title"><i class="dropdown icon"></i> Descripcion </div>
                             <div class="content">
                               <p class="transition hidden"><%= publication.description %></p>
                             </div>
                         </div>
                       </div>
                   </div>

                 </div>
               <% end %>
              <%end%>
            </div>
            <%if current_user.has_role? :Administrador or current_user.has_role? :Modificador %>
            <div class="ui center aligned basic segment">
              <%= link_to 'Agragar Publicacion', new_publication_path , class:"ui green button " %>
            </div>
            <%end%>

  </div>
</div>

<br>

app/views/publications/new.html.erb
<%= render 'form' %>